- name: Playbook test
  hosts: back
  become: yes

  tasks:

    - name: Show message
      debug:
        msg: "Testing, testing..."

    - name: Create user
      user: 
        name: "{{ item }}"
        create_home: yes
      loop:
        - Pepe
        - Paco
