- name: Playbook test
  hosts: all
  become: yes

  tasks:

    - name: Show message
      debug:
        msg: "Testing, testing..."

    - name: Create user
      user: 
        name: my_user
        create_home: yes